config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :users
    resources :activities  do
      resources :bookings, only: [ :create ]
      resources :reviews, only: [ :new, :create, :index ]
  end
  resources :pages, only: [:home]
  resources :bookings, only: [ :index, :destroy]
  get '/search' => 'pages#search', :as => 'search_page'
end

app/models/activity.rb
class Activity < ApplicationRecord
  geocoded_by :activity_address
  after_validation :geocode, if: :will_save_change_to_activity_address?
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  belongs_to :category
  has_many_attached :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :activities
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :activities
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = policy_scope(Activity).page params[:page]
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude
      }
    end
  end


  def new
    @activity = Activity.new
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    authorize @activity
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render 'new'
    end
  end

  def show
    @user = @activity.user
    @booking = Booking.new
    @reviews = Review.where(activity_id: params[:id])
    @markers = [{  lat: @activity.latitude, lng: @activity.longitude }]
  end


  def edit
    authorize @activity
  end

  def update
    @activity.update(activity_params)
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  def activity_params
    params.require(:activity).permit(:title, :who_description, :why_description, :what_description, :meeting_address, :activity_address, :capacity, :capacity, :donation, :start_date, :end_date, :requirements, :category_id, :website, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :photo, :persona_description])
  end

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController



  def create
    @booking = Booking.new(booking_params)
    @activity = Activity.find(params[:activity_id])
    @user = current_user
    @booking.activity = @activity
    @booking.user = @user
    authorize @booking
    if @booking.save
      render 'shared/booking_confirmation'
      @activity.capacity -= 1
    else
      render 'activities/show'
    end
  end

  def index
    @bookings= policy_scope(Booking)

    @past_bookings = Booking.where('start_date < ?', DateTime.now)
    @upcoming_bookings = Booking.where('start_date > ?', DateTime.now)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @activity = @booking.activity
    authorize @booking
    @booking.destroy
    @activity.capacity += 1
    redirect_to activity_path(@activity)
  end

private

 def booking_params
  params.require(:booking).permit(:start_date, :end_date)
 end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def search
    if params[:search].blank?
    redirect_to(root_path, alert: "Empty field!")
    else
    @parameter = params[:search]
    @results = Activity.where("(who_description) ILIKE ?", "%#{@parameter}%")
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @activity = Activity.find(params[:activity_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @activity = Activity.find(params[:activity_id])
    @review.activity = @activity
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def index
    #all_reviews = policy_scope(Review)
    #@reviews = all_reviews.where(activity_id: params[:activity_id])
    @activity = Activity.find(params[:activity_id])
    @reviews = policy_scope(Review).where(activity: @activity)
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    raise
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/activities/_form.html.erb
<div class="form-create-activity">

<%= simple_form_for(@activity) do |f| %>
  <%= f.input :title %>
  <%= f.input :category_id, collection: Category.all %>
  <%= f.input :website %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.input :who_description %>
  <%= f.input :why_description %>
  <%= f.input :what_description %>
  <%= f.input :meeting_address %>
  <%= f.input :activity_address %>
  <%= f.input :capacity %>
  <%= f.input :donation %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :requirements %>

  <div class="create-btn" >
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

</div>

app/views/activities/edit.html.erb
<%= render "form", activity: @activity %>

app/views/activities/index.html.erb
<div class= "container-fluid">

  <div class= "row m-3" >
    <div class= "col-md-6"><h1 class="m-5 p-5">Find the activities in your city below</h1> </div>
      <div class= "col-md-6 mb-2" id="map"
      style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

  <div class= "index-cards-container" >
    <% @activities.each do |activity| %>

    <div class="card-container">

        <div class="cards-image-container">
          <%= cl_image_tag(activity.photos[0].key)%>
        </div>

          <div class="card-text-container col-8">
            <div class="cards-title-container">
              <h3> <%= link_to activity.title, activity_path(activity) %> </h3>
            </div>
            <div class="cards-description-container">
              <p> <%=h truncate(activity.who_description, :length => 300) %></p>
            </div>
            <div class="cards-category-container">
              <p> Category: <%= activity.category.name %></p>
            </div>
          </div>

        <div class="cards-review-container">

        <% if activity.reviews[0] %>
        <div class="stars-container">
          <% count = 0 %>
          <% 5.times do %>
            <% if activity.reviews[0].rating > count %>
              <i class="fas fa-star mt-3"></i>
            <% else %>
              <i class="far fa-star mt-3"></i>
            <% end %>
            <% count += 1 %>
          <% end %>
        </div>
          <p class="mt-3 mx-4">"<%=h truncate(activity.reviews[0].description, :length => 100) %>"</p>
          <p class="text-right mx-4"><%= activity.reviews[0].user.nickname %></p>
        <% end %>
        </div>
    </div>
    <% end %>


  <%= paginate @activities %>

</div>

app/views/activities/new.html.erb
<%= render "form", activity: @activity %>

app/views/activities/show.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<div class="show-page-title-container">
    <h1><%= @activity.title %></h1>
</div>

<div class= "container mt-4">
  <div class="row">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
         <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
    <div class="carousel-inner" id="carousel" style="height: 500px; width: 100%">
      <div class="carousel-item active">
        <%= cl_image_tag(@activity.photos[0].key)%>
      </div>
        <% @activity.photos.each do |photo| %>
          <div class="carousel-item">
            <%= cl_image_tag(photo.key)%>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

<div class= "container mt-4">
     <div class="ml-3 mt-2 mb-0" id="map"
        style="width: 45%; height: 330px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    <div class="col-md-6 mt-2" id= "user-info">
      <% if @activity.reviews.any? %>
        <% count = 0 %>
        <% 5.times do %>
          <% if (@activity.reviews.pluck(:rating).inject(:+)/(@activity.reviews.count).to_f).ceil > count %>
            <i class="fas fa-star"></i>
          <% else %>
            <i class="far fa-star"></i>
          <% end %>
          <% count += 1 %>
        <% end %>
        <p><%= link_to "(Check reviews)", activity_reviews_path(@activity) %></p>
      <% else %>
        <i class="far fa-star"> </i> <i class="far fa-star"> </i> <i class="far fa-star"> </i> <i class="far fa-star"> </i> <i class="far fa-star"> </i>
        <p> This activity has no reviews <%= link_to "(Add one)", activity_reviews_path(@activity) %></p>
      <% end %>
      <h2>This activity was created by <%= @user.nickname %></h2>
      <p>Click on the avatar to chat with him</p>

      <div class="row">
        <div class="col-9">
          <div class= "user-description">
            <p> <%= @activity.user.persona_description %> </p>
            <p> Category: <%= link_to @activity.category.name, activity_path(@activity.category) %></p>
            <p>Web site available: <%= link_to @activity.website, @activity.website %></p>
          </div>
        </div>
        <div class="profile-picture col-3 ">
          <%= cl_image_tag(@activity.user.photo.key) if @activity.user.photo.attached? %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="show-text-container">
  <div class="first-texts-container">
     <div class="col-2 align-self-center"> <h2 class="ml-5" id="show-titles">Who</h1></div>
     <div class="col-10"> <p id="show-texts"><%= @activity.who_description %></p></div>
   </div>
   <div class="second-texts-container">
     <div class="col-2 align-self-center"> <h2 class="ml-5" id="show-titles">Why</h1></div>
     <div class="col-10"> <p id="show-texts"><%= @activity.why_description %></p> </div>
  </div>

  <div class="third-texts-and-booking-container">
    <div class="third-texts-container">
      <div class="what-container">
        <div class="col-2 align-self-center"> <h2 class="ml-5" id="show-titles">What</h1></div>
        <div class="col-10"> <p class="ml-5 pl-4" id="show-texts"><%= @activity.what_description %></p></div>
      </div>
      <div class="when-container">
        <div class="col-2 align-self-center"> <h2 class="ml-5" id="show-titles">When</h1></div>
        <div class="col-10 align-self-center"> <p class="d-inline ml-5 pl-4"id="show-texts">From: <%= @activity.start_date %></p>
        <p class=" d-inline" id="show-texts">To: <%= @activity.end_date %></p></div>
      </div>
      <div class="where-container">
        <div class="col-2 align-self-center"><h2 class="ml-5" id="show-titles">Where</h1></div>
        <div class="col-10 align-self-center"><p class=" ml-5 pl-4 id="show-texts">Meeting point: <%= link_to @activity.meeting_address %></p>
        <p class="ml-5 pl-4 " id="show-texts">Activity: <%= link_to @activity.activity_address %></p></div>
      </div>
      <div class="donations-container">
       <div class="col-2 align-self-center"> <h2 id="show-titles">Donation</h1></div>
        <div class="col-10 align-self-center"><p class=" ml-5 pl-4" id="show-texts">$<%= @activity.donation %>.00</p></div>
      </div>
         <h4 class=" pl-3" id="show-titles">Requirements for this activity:</h4>
         <p class=" pb-4 pl-3" id="show-texts"> <%= @activity.requirements %></p>

    </div>
    <div class="bookings-container pl-5">
      <div class="col-10">
      <h2>Book</h1>
      <%= simple_form_for([@activity, @booking]) do |f| %>
        <%= f.input :start_date, wrapper_html: { class: 'flex-select' }, as: :date, html5: true %>
        <%= f.input :end_date, wrapper_html: { class: 'flex-select' }, as: :date, html5: true %>
        <%= f.button :submit, "Book", class: "btn btn-primary btn-block", style: "margin-bottom: 20px;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row mt-5 pt-5">
    <div class="col-12 mt-5"> <h3>Upcoming bookings</h3>
    </div>
  <% @upcoming_bookings.each do |booking| %>
  <br> </br>
    <div class="col-12">
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%= cl_image_tag(booking.activity.photos[0].key, {:style => "height: 180px"})%>
          </div>
        <div class="col-md-8">
          <div class="card-body">
            <h4 class="text-left">  <%= booking.activity.title %> </h4>
            <p class="card-text"> <%= booking.activity.description %> </p>
            <p class="card-text"><small class="text-muted">
            <%= booking.start_date %> |
            <%= booking.end_date %></small></p>
            <%= link_to "Cancel booking",
            booking_path(booking),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


    <div class="col-12 mt-4">
      <h3>Past events</h3>
    </div>

<% @past_bookings.each do |booking| %>

   <div class="col-12">
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
       <div class="col-md-4">
        <%= cl_image_tag(booking.activity.photos[0].key, {:style => "height: 180px"})%>
       </div>
       <div class="col-md-8">
        <div class="card-body">
          <h4 class="text-left">  <%= booking.activity.title %> </h4>
          <p class="card-text"> <%= booking.activity.description %> </p>
          <p class="card-text"><small class="text-muted">
            <%= booking.start_date %> |
            <%= booking.end_date %></small></p>
            <%= link_to "Add Review", new_activity_review_path(booking.activity.id) %>
        </div>
      </div>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cooltiva-Social</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
  <div class="bodyflex">

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </div>

    <%= render 'shared/footer' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner_h">
  <div class="container">
    <div class="content-banner">
      <section class="rw-wrapper">
        <h1 class="rw-sentence" id="home-white-text">
        <span>Helping is</span>
        <div class="rw-words rw-words-1">
        <span>fortunate</span>
        <span>cool</span>
        <span>incredible</span>
        <span>the right thing to do</span>
        </div>
        </h1>
      </section>
      <p id="home-white-text">The directory of volunteering, find your favorite and improve society together</p>
      <a href="/users/sign_up">
      <button type="button" class="btn btn-primary">  Register now!   </button>
      </a>
      <!-- [...] -->
      <%= form_tag(search_page_path, :method => "get", class: '123') do %>
        <div class="search">
          <input type="search" class="search-box" name="search">
          <span class="search-button">
            <span class="search-icon"></span>
          </span>
        </div>
      <% end %>


    </div>
  </div>
</div>





<div class="container-cards-title">
  <h1>Discover projects and organizations looking for you</h1>
<div class="container-cards">
<div class="d-flex justify-capontent-center">

    <div class="card min-vh-40 d-inline-block h-70" style="width: 18rem;">
      <div style="background-image: url('https://i.ibb.co/FhDCFLy/240320-covid19greeting-LHL.jpg')" class="img-card card-img-top" alt="..."> </div>
        <div class="card-body text-center">
        <h5 class="card-title">Assist</h5>
        <p class="card-text">Volunteer for different events and causes and make new friends!</p>

        </div>
    </div>

    <div class="card min-vh-40 d-inline-block h-70" style="width: 18rem;">
      <div style="background-image: url('https://i.ibb.co/M7vjsbF/geocoding.png')" class="img-card card-img-top" alt="..."> </div>
        <div class="card-body text-center">
        <h5 class="card-title">Find</h5>
        <p class="card-text">Search for the nearest places, could be your house or when you travel!</p>
        </div>
    </div>

    <div class="card min-vh-40 d-inline-block h-70" style="width: 18rem;">
      <div style="background-image: url('https://i.ibb.co/Hd37tjm/Screen-Shot-2020-05-16-at-4-12-00-AM.png')" class="img-card card-img-top" alt="..."> </div>
        <div class="card-body text-center">
        <h5 class="card-title">Shop</h5>
        <p class="card-text">Buy on social responsible sites or markets</p>
        </div>
    </div>

    <div class="card min-vh-40 d-inline-block h-70" style="width: 18rem;">
      <div style="background-image: url('https://i.ibb.co/vXPcXwf/text-chemistry-review.jpg')" class="img-card card-img-top" alt="..."> </div>
        <div class="card-body text-center">
        <h5 class="card-title">Reviews</h5>
        <p class="card-text">Tell us how was your experience so others get motivated to join!</p>
        </div>
    </div>

</div>
</div>
</div>

<div class="categories d-flex justify-content-center">
<div class="container-categories border text-center">
  <h1>Our categories</h1>
  <div class="categories-title">
    <div class="d-flex justify-content-around">
      <a href="" class="category d-inline-block"> Responsible consumption </a>
      <a href="" class="category d-inline-block"> Donations </a>
      <a href="" class="category d-inline-block"> Social Working</a>
      <a href="" class="category d-inline-block"> Shared Knowledge</a>

    </div>
  </div>
</div>
</div>

<div class="d-flex justify-content-center">
<div class="card-notsure card bg-light text-white text-center">
  <img src="https://i.ibb.co/r6560B3/techo.jpg" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h1 class="card-title" id="notsuretitle">Not sure where to begin?</h1>
    <p class="card-text" id="home-white-text">Start with the list of activities near your location</p>
    <a href="#" class="btn btn-primary">Start here!</a>
  </div>
</div>
</div>

app/views/pages/search.html.erb
<div class="search-page-container">
  <h3>Search Result</h3>
  <div class="search-results-container">
    <% @results.each do |result| %>
      <div class="search-title-result mt-3" >
        <h5> <%= link_to result.title, activity_path(result.id) %></h5>
      </div>
      <div class="search-description-result">
        <%= result.who_description %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="reviews-index-container">
  <div class="reviews-title-container">
    <h1 class="text-center"> Star Rating of: <%= @activity.title %></h1>
  </div>

  <div class="review-list-container">
    <% @reviews.each do |review| %>

      <div class="review-card-container">
        <div class="review-profile-pic-container mr-4">
          <%= cl_image_tag(review.user.photo.key) if review.user.photo.attached? %>
        </div>
          <div class="nickname-review-container text-center mt-4">
            <p> # days ago </p>
            <h3><%= review.user.nickname %></h3>
          </div>
            <div class="text-and-stars-container">
              <div class="stars-container">
                <% count = 0 %>
                  <% 5.times do %>
                    <% if review.rating > count %>
                      <i class="fas fa-star"></i>
                    <% else %>
                       <i class="far fa-star"></i>
                    <% end %>
                    <% count += 1 %>
                  <% end %>
              </div>
              <div class="text-review-container align-middle">
                <p>"<%= review.description %>"</p>
              </div>
            </div>
      </div>

    <% end %>
  </div>

</div>

  <div class="btn btn-primary" id="new-review-btn">
    <%= link_to "Add Review", new_activity_review_path(@activity), :class => "btn text-white" %>
  </div>

app/views/reviews/new.html.erb
<div class="new-review-container">
<div class="new-review">

  <div class="review-form" align="center">
    <h3>Review <%= @activity.title %></h3>
    <br/><br/>
    <%= simple_form_for [ @activity, @review ] do |f| %>
      <%= f.input :description %>
      <%= f.input :rating, collection: 0..5 %>
      <%= f.submit "Submit review", class: "btn btn-primary"%>
  <% end %>
  </div>

</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer">

  <div class="address-and-form-container">
    <div class="address-text-container">
      <div class="address-text">20 Leeton Ridge St. Oklahoma City, OK 73112 hello@cooltivasocial.com </div>
    </div>
      <div class="form-container">
        <div class="suscribe-text">Suscribe </div>
        <form class="input-group form-check-inline">
        <input type="text" class="form-control form-control-sm col-11" placeholder="Your email"
          aria-label="Your email" aria-describedby="basic-addon2">
          <button class="button-form btn btn-primary">Sign up!</button>
        </form>
    </div>
  </div>

  <!-- Copyright and icons -->
    <div class="copyright-and-icons-container">
      <div class="container-copyright-text">
        <div class="copyright-text">© 2020 Copyright: <a href=""> Cooltiva-Social.inc</a></div>
      </div>
        <div class="icons-container">
          <i class="fab fa-facebook-f fa-2x white-text"> </i>
          <i class="fab fa-twitter fa-2x white-text"> </i>
          <i class="fab fa-instagram fa-2x white-text"> </i>
        </div>
    </div>

</footer>

app/views/shared/booking_confirmation.html.erb
<div class= container-sm>
  <div>
  <h3>
    Booking confirmed
  </h3>
  <p>Congratulations! You have successfully booked your slot</p>
 <a class="btn btn-primary" id="abc" href="/bookings">View my bookings </a>

</div>